language: php
php:
- 7.0
script:
- find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/wpmktgengine-extension-jvzoo-integration/
  - secure: nqxFubpAN+t6aG+4s2/RVCcxEX6slUYvNzYLZ4QrYvOkFp+FUS0m82Vu3B9x7jZMf8QgqcnnWcgbG8l4/GUkJHM+NXA0oTsVScLZlySGJ76D3mTdCTKQ+zgLZ1PJU2I4XsPVcbS/8zyCp7hazBovVtacnRq6O+GkUTpTvaawyx4wyOFZR7iDI8r+N5sWDmcACNcP1zRN5yAfx2I7ryLEhmL3J61NvFaoLCcaZ9AssmUcH0UTmmnRokHHHmx8nvpXqMG6JPG1UgFSvLhuRJH3nM0uny+U722TK5h+Bb5USYj0Ylqen665egi6gnZHmFJ+LTFz4UPNiPmLgLXIiKldd/UshlZ7VBk8WIj0pTG1Y0hl1RtLqzlhOPM3fxUebvErfVayFvEeAsrNWoBO9cgBsio94UD+zQUeENZ5zYu26lzdFwGiuoRoHm8/Kk0DEBhsx68jgxpWRtbmvDfgaU3gLAMmZKDQjyrN/aEhTO9Qc7P0TZHDxW6vVMtrEWqgTiAlJ63/aJ66HuKKvGdaUn2+vhnY1WFikeLJTnDDY3vKH09TgLmWkolB5gfUtiI28cmvRgROSssRVmkw48+NfBiCycv7G7T5iW0eZ8dBxC0IZVkhziobnqEBFxl8amQD0+aOsh0IF1TAuYiQS8IiNIsDaOL5ozMMYFP5/Qc0ZH1EYnY=
  - secure: i1HMbcnJvyV3ZWhdI2nNdIsIOA2HY3GhFy+ldPR+zioQbDpBJzMOOe7FaCtSeolA1grtAMVwoILeAfWwiGF6s6BA0oKqySNNa6Za/CHNF2qfFXyF3Lang3AkuER+lZL9zHgtwR5uygUwX7Sxjti3rJkLJ4F6VsiggrzFEE66+8/LUghwfexZAZa+TDkTlchWKj74FXUfBcbIbt1dHIEsEsoudweDRK1i5sdO9WmSAr0qxDZkeRgT7Wmw6JfLlXukPfuNh/FKtsVvwptrhsAUV4ZrJ7/9W7qI4zMmnGaKWXzBW67PIuqooS8hbyYwPihx1u0Y9AD+XRsj8tLZcYK081A1tBLZumcqBbZnm7s0QXze1A2MPOqWwJO+hFOBpYpMef7oPITjz2fTS3mNAG3OeXR8oJTDp7ppMdmfHSLe5UjZh7pMzcdGqMexgpwqCuIkhdPrN17s0Jmj1/zGXIIoqDPqp4bV0TDxQMFUhveWUkfyws4rJPpCCU2dKTOGk5lcVnKPK0V4NkceZkc/VoJTTweAa31328v3c0Trb21HcFGk+QR0I3ioedkSLwFFHQkHe12sEPCAhOH49da7LszCfkOtha2F1olOqT9ys0hEdYRpYVNYbX4mV+MxwnRU0MnanrUl16pPqDDQvmwsv44H8ZqwJW31xwy3q/NJzMtUoYM=
